run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - errcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

